7.x-BPL
discoverygarden/platform_main_feature pull request #161
Opened 2017-05-19 17:07 UTC by MorganDawe

2017-05-24 16:54 UTC, jordandukart requested changes

2017-05-24 16:54 UTC, jordandukart commented on platform_main_feature.features.menu_links.inc
> -    'link_path' => 'uuid/node/3dfbfeaf-cb77-4ac0-b16f-145af17649b5',
No longer uuided?

2017-05-24 16:54 UTC, jordandukart commented on platform_main_feature.features.menu_links.inc
> +  $menu_links['menu-footer-menu_researchers:node/2'] = array(
No uuids?

2017-05-24 16:54 UTC, jordandukart commented on platform_main_feature.features.menu_links.inc
> +  $menu_links['menu-footer-menu_policies:node/10'] = array(
UUID.

2017-05-24 16:54 UTC, jordandukart commented on platform_main_feature.features.menu_links.inc
> +    'hidden' => 0,
Not hidden anymore?

2017-05-24 16:54 UTC, jordandukart commented on platform_main_feature.features.user_permission.inc
> -  // Exported permission: 'export islandora bookmarks'.
Nuking permissions?

2017-05-25 14:45 UTC, MorganDawe commented on platform_main_feature.features.user_permission.inc
> -  // Exported permission: 'export islandora bookmarks'.
Looks like the permissions are being handled in the bpl permissions feature

2017-05-26 14:55 UTC, merged